version: "3.2"

services:
  php:
    build: docker/php
    volumes:
      - ./:/app
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mongodb:/data/db
